Repository Ousret/kiss-headers, pull requests merged in 2020-03, with the labels that each got.

#2 First batch of bug fixes after initial release 1.0.0
  README.md
  kiss_headers/utils.py
  kiss_headers/version.py
Labels: bug, documentation, enhancement

#3 Second batch of bug fixes and features add
  README.md
  kiss_headers/utils.py
  kiss_headers/version.py
  setup.py
Labels: bug, documentation, enhancement

#4 Bring new minors features and fix minors bugs
  README.md
  kiss_headers/utils.py
  kiss_headers/version.py
  tests/test_headers_operation.py
  tests/test_headers_reserved_keyword.py
Labels: bug, documentation, enhancement

#5 working on 1.1.0
  kiss_headers/__init__.py
  kiss_headers/utils.py
  tests/test_headers_from_string.py
  tests/test_headers_operation.py
  tests/test_with_http_request.py
Labels: bug, documentation, enhancement

#7 :heavy_minus_sign: Removing all dependencies
  kiss_headers/structures.py
  kiss_headers/utils.py
  setup.py
Labels: enhancement

#8 :sparkle: Add the possibility to assign attribute of an Header
  kiss_headers/utils.py
  tests/test_header_operation.py
Labels: enhancement

#9 ✏️Grammar changes to docs
  CONTRIBUTING.md
  README.md
  docs/advanced-header.md
  docs/advanced-headers.md
  docs/contributing.md
  docs/imap.md
  docs/index.md
  docs/quickstart.md
Labels: documentation, good first issue

#10 Release 1.1.1
  .travis.yml
  README.md
  kiss_headers/__init__.py
  kiss_headers/structures.py
  kiss_headers/utils.py
  kiss_headers/version.py
  setup.py
  tests/test_case_insensible_dict.py
  tests/test_headers.py
  tests/test_headers_from_string.py
  tests/test_with_http_request.py
Labels: enhancement
